"""
Django settings for MBEx project.

Generated by "django-admin startproject" using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from django.conf.global_settings import SESSION_EXPIRE_AT_BROWSER_CLOSE

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent

#Django가 세션을 쿠키에 넣어 두기 때문에 해당 설정을 넣어주는 것.
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

#Logging
import os
#logger.debug()
#logger.info()
#logger.warning()
#logger.error()
#logger.critical()
LOGGING = {
    "version":1,
    "disable_existing_loggers":False,
    "formatters":{
        "format1":{
            "format":"[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            "datefmt":"%Y-%m-%d %H:%M:%S",
            },
        "format2":{
            "format":"%(levelname)s %(message)s"
            },
        },
    "handlers":{
        "file":{
            "level":"INFO",
            "class":"logging.handlers.RotatingFileHandler",
            "filename":os.path.join(BASE_DIR, "log/logfile.log"),
            "encoding":"UTF-8",
            "maxBytes":1024*1024*5, #5MB
            "backupCount":3,
            "formatter":"format1",
            },
        "console":{
            "level":"DEBUG",
            "class":"logging.StreamHandler",
            "formatter":"format2",
            },
        },
    "loggers":{
        "django":{
            "handlers":["console"],
            "propagate":True,
            "level":"WARNING",
            },
        "django.request":{
            "handlers":["console"],
            "propagate":True,
            "level":"WARNING",
            },
        "member":{
            "handlers":["file"],
            "propagate":True,
            "level":"INFO", #로그 쌓을때    debug하면 다 쌓임.
            },
        "board":{
            "handlers":["file"],
            "propagate":True,
            "level":"INFO",
            }
        },
    }


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-452q@ddpf4)o&x9)8*)z!*63378w4(*%e-gl2dm)tsc5m$tk9#"

# SECURITY WARNING: don"t run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1","192.168.56.1", "192.168.0.8"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    #1201 added
    "member.apps.MemberConfig",
    #1206 added
    "board.apps.BoardConfig",
    #1207 added
    "mathfilters",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    #add
]

ROOT_URLCONF = "MBEx.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True, #False 일 경우 template을 한데 모을 수 있음.
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "MBEx.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

#LANGUAGE_CODE = "en-us"
LANGUAGE_CODE="ko-kr"
#TIME_ZONE = "UTC"
TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
#외부 URL     css js images 각각의 폴더 생성하여 집어 넣을 것임.
STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
